### ISSUE TITLE
Setup does not work

### ISSUE THREAD

**Issue by TechGeek285** [jonathonor/syncBot#12]
Whenever i run the register .js it does not go fuly. See pic 
![Screenshot 2022-03-28 180251](https://user-images.githubusercontent.com/96345070/160450079-ca68786d-6865-460e-ab22-f4fb1c12d1b7.jpg)

**Comment by MrYoung09** [comment]
same

**Comment by jonathonor** [comment]
I will go back through the documentation and specify this. Register uses the server1id from the config file. From the error message I can see you do not have it set.

**Comment by TechGeek285** [comment]
I had to change in the register from server1id to main server ID. it now works but comes up with a load of error messages before shutting off.
Can you fix this?

**Comment by TechGeek285** [comment]
Yes. Give me a moment It is quite long @jonathonor

**Comment by TechGeek285** [comment]
![image](https://user-images.githubusercontent.com/96345070/162971394-61fd4c11-72e8-4684-a4d2-a0ad58be1da4.png)
![image](https://user-images.githubusercontent.com/96345070/162971414-32c1640a-041d-4c66-b512-38bc191f503b.png)
![image](https://user-images.githubusercontent.com/96345070/162971436-f29fb186-f06a-4ce6-abd6-baf024392563.png)
![image](https://user-images.githubusercontent.com/96345070/162971453-5943dd84-e892-4eaf-8714-ce1263a646ba.png)
![image](https://user-images.githubusercontent.com/96345070/162971466-d742fa87-5d2c-46da-9bc4-98d13053b00f.png)
![image](https://user-images.githubusercontent.com/96345070/162972456-75d08f4f-bccd-4ee8-ae73-42f010b5f422.png)

**Comment by TechGeek285** [comment]
That is some of it @jonathonor

**Comment by TechGeek285** [comment]
I replaced them and it still doesn’t work. It gives the role in all servers, gives that massive error then shuts off.

**Comment by jonathonor** [comment]
@TechGeek285 After running register.js to register the commands on your server, are you then running run.js and leaving it running to apply the roles? If so, please provide the error that the bot fails with so I can help.

**Comment by jonathonor** [comment]
@MrYoung09 please verify this is now fixed

**Comment by jonathonor** [comment]
@TechGeek285 were you able to resolve the problem? If not please reach out and I would be to happy to help on my discord server.

https://discord.gg/f8SUVvQZD3
