### ISSUE TITLE
Not able to register the bot.

### ISSUE THREAD

**Issue by Mohta69** [jonathonor/syncBot#14]
![Screenshot 2022-04-15 at 11 47 16 PM](https://user-images.githubusercontent.com/63720850/163606508-62757b54-f83d-4f19-8a57-fcefa20edac3.png)
I tried running "node register.js" but got the error. I've made sure everything is fine and I have even set up config.json properly.

**Comment by jonathonor** [comment]
@Mohta69 This is my mistake, I am uploading a new version of the example register.js script now. It is using an old version of the config instead of the new one. If you would like to fix it yourself, it should be as easy as swapping config.server1id in register.js for config.mainserver

**Comment by Mohta69** [comment]
Alright my guy

**Comment by Mohta69** [comment]
Hey!
I tried running the newest version on this repo with everything set up properly, I'm facing an issue:
![Screenshot 2022-04-16 at 11 16 04 AM](https://user-images.githubusercontent.com/63720850/163663400-47de8506-059c-4b65-9df8-1430b528df0e.png)

**Comment by jonathonor** [comment]
@Mohta69 when you invited the bot to your server, make sure you enabled the application.commands permission.

Here is an excerpt from the dev docs.
In order to make commands work within a guild, the guild must authorize your application with the applications.commands scope. The bot scope is not enough

**Comment by Mohta69** [comment]
Now, "node register.js" does work but when I tried "node run.js" it reverted the following:
![Screenshot 2022-04-16 at 7 48 59 PM](https://user-images.githubusercontent.com/63720850/163678594-46cc1ebc-140a-4de3-8f9d-7e870223f7f4.png)

**Comment by jonathonor** [comment]
@Mohta69 make sure you have the SyncBot role higher in the hierarchy of roles than the roles you are having the bot assign.

**Comment by Mohta69** [comment]
@jonathonor Yes, syncBot's role is higher than every other role in both servers, yet I'm facing the same issue.

**Comment by jonathonor** [comment]
Hmm ok, then likely when the bot was invited it was still missing permissions, did you select view audit log, application.commands, and manage roles when you invited it?

**Comment by jonathonor** [comment]
If that doesn't work I'll go through the setup and make a YouTube video.

**Comment by Mohta69** [comment]
Yes, I have made sure everything was set up properly.

**Comment by jonathonor** [comment]
Ok, give me a little bit, I'll make a video and see if we can't track down what I missed when writing the docs.

**Comment by Mohta69** [comment]
Sure

**Comment by Mohta69** [comment]
Do you have a discord where we can talk with ease?

**Comment by jonathonor** [comment]
jonathon#0110

**Comment by Mohta69** [comment]
added

**Comment by jonathonor** [comment]
Closing this issue as the problem ended up being in the config syncedServers being sent as numbers instead of a string
syncedServers: ["1234567890"] is correct, syncedServers: [1234567890] is incorrect.
