### ISSUE TITLE
sync roles request

### ISSUE THREAD

**Issue by gitagogaming** [jonathonor/syncBot#5]
ability to sync roles on MAINSERVER based on what server the person is in out of a list of 15 other servers...   

this would help sort members on a specific team thats located in the 'main hub'

**Comment by jonathonor** [comment]
@gitagogaming Could you give an example of the functionality you would like added?

**Comment by jonathonor** [comment]
Closing this issue as this is now possible with reverseSync.js Please see www.jonsbots.com/syncbot for more information.

Say you have a main server named "All Teams"
And you have synced servers
1. Team 1
2. Team 2
3. Team 3
4. Team 4 ... 

On each of the synced servers, you would make a role denoting that server (every member in server Team 1 has role Team 1
In the main server you have all roles Team 1 through Team 15.

With the reverse sync, when you give a member a role in any of the 15 synced servers, they would get the role with the same name in the main server.
