### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by godofclashcr** [jonathonor/syncBot#9]
Hello there, 
the bot doesnt really work, because he is offline, 
did i do something wrong?

Is this correct, how i did fill it in?
`
    "token": "OTQxMjg5MDYwNTkxMzUzODc2.YgTxwA.Fc5_F0w6d9EzaZ2DUqyhyAFsiFg",
    "clientId": "941289060591353876",
    "mainServer": "724366785993768991",
    "syncedServers": "824542691882303500",
    "commanderRole": "●Ely | eSports","●Ely | Academy",
    "logChannelId": "901818092395561021
}
`

**Comment by godofclashcr** [comment]
@jonathonor

**Comment by jonathonor** [comment]
Hi, do you get any error when trying to start up the bot? It looks like you are missing a " after the logChannelId

**Comment by EchoeMatrix** [comment]
@jonathonor what should I put in place of language : "" and run : ""

**Comment by jonathonor** [comment]
> @jonathonor what should I put in place of language : "" and run : ""

I do not follow the question? In what file are you adding this?

**Comment by Mohta69** [comment]
I think they are trying to add it on replit

**Comment by jonathonor** [comment]
Hmm, I would need some more context to be able to help.

**Comment by jonathonor** [comment]
@godofclashcr @EchoeMatrix have your issues been solved?

**Comment by EchoeMatrix** [comment]
> @godofclashcr @EchoeMatrix have your issues been solved?

Idk ask @Mohta69 he's working on the fix for me

**Comment by jonathonor** [comment]
Closing this issue as Mohta and I found the problem.
